### ISSUE TITLE
Hanil GSoC 2024

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2076]
#### Project 1: Implement Asynchronous Notifications

**Objective:** Enhance BLT’s user experience with asynchronous notifications.

**Tasks:**

1. **Setup Django Channels:**
   - [x] OWASP-BLT/BLT#2213
   - [x] OWASP-BLT/BLT#2214
   - [x] OWASP-BLT/BLT#2215

2. **Implement WebSocket Notifications:**
   - [x] OWASP-BLT/BLT#2216
   - [x] OWASP-BLT/BLT#2217
   - [x] OWASP-BLT/BLT#2218

3. **Implement Celery and Redis:**
   - [x] OWASP-BLT/BLT#2219
   - [x] OWASP-BLT/BLT#2220

4. **Context Processor Improvements:**
   - [x] OWASP-BLT/BLT#2221

5. **Future Improvements:**
   - [x] OWASP-BLT/BLT#2222

#### Project 2: Spam Detection Model

**Objective:** Implement a robust spam detection system using machine learning.

**Tasks:**

1. **ML Models Implementation:**
   - [ ] OWASP-BLT/BLT#2223
   - [x] OWASP-BLT/BLT#2224
   - [x] OWASP-BLT/BLT#2225
   - [x] OWASP-BLT/BLT#2226

2. **Human Review Layer:**
   - [ ] OWASP-BLT/BLT#2227
   - [x] OWASP-BLT/BLT#2228

3. **Community Reporting Layer:**
   - [ ] OWASP-BLT/BLT#2229

4. **Future Improvements:**
   - [ ] OWASP-BLT/BLT#2231
   - [ ] OWASP-BLT/BLT#2230

#### Project 3: Trademark Defense Project

**Objective:** Help companies manage their trademarks and protect against squatting.

**Tasks:**

1. **Trademark Database:**
   - [ ] OWASP-BLT/BLT#2232
   - [x] OWASP-BLT/BLT#2233

2. **Company Management:**
   - [x] OWASP-BLT/BLT#2234
   - [x] OWASP-BLT/BLT#2235

3. **Squatting Reports:**
   - [x] OWASP-BLT/BLT#2236

4. **Future Improvements:**
   - [x] OWASP-BLT/BLT#2237

#### Project 4: BLT Private Project

**Objective:** Implement secure private bug reporting functionality.

**Tasks:**

1. **Google Cloud Buckets:**
   - [ ] OWASP-BLT/BLT#2238
   - [x] OWASP-BLT/BLT#2239

2. **Private Report Management:**
   - [ ] OWASP-BLT/BLT#2240
   - [x] OWASP-BLT/BLT#2241

3. **Alternative Storage Options:**
   - [x] OWASP-BLT/BLT#2242

#### Project 5: Chrome Extension

**Objective:** Develop a Chrome Extension for BLT to provide CRM-style bug management.

**Tasks:**

1. **Manifest V3 Support:**
   - [x] OWASP-BLT/BLT#2243

2. **Feature Development:**
   - [x] OWASP-BLT/OWASP-BLT-API#3
   - [x] OWASP-BLT/BLT#2245
   - [x] OWASP-BLT/BLT-Extension#23
   - [x] OWASP-BLT/BLT#2247

3. **Testing and Publishing:**
   - [x] OWASP-BLT/BLT#2248
   - [ ] OWASP-BLT/BLT-Extension#22

4. **Future Improvements:**
   - [ ] OWASP-BLT/BLT-Extension#21

### Timeline and Milestones
1. **Pre-GSOC Period:**
   - Complete initial research and proofs-of-concept.
2. **Community Bonding (May 1 - May 26):**
   - Collaborate with mentors and refine designs.
3. **Phase 1 (May 27 - July 11):**
   - Implement asynchronous notifications.
   - Develop spam detection models and human review layers.
4. **Phase 2 (July 12 - Aug 19):**
   - Complete the Trademark Defense Project.
   - Implement BLT Private Project.
   - Build the Chrome Extension.
