### ISSUE TITLE
Mohit Anand - Enter in all of your tasks from your proposal into Github - split them into the weekly milestones

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#331]
https://drive.google.com/open?id=0BwuhDpZmwRi1OWprU3dzM3o0MGM
[owasp7.pdf](https://github.com/OWASP/BLT/files/1133557/owasp7.pdf)

**Comment by seanauriti** [comment]
@farziengineer can you please add these to github under separate issues or at least make this a task list and show what you have done so far? Because this will help track progress for the evaluations.

**Comment by farziengineer** [comment]
**Until Mid-Evaluation**
- [x] . Gamification of bugheist.com by providing badges(Gold,Silver,Bronze)
- [x] . User profiles would include information regarding types of bugs found.
- [x] . Comment add without refresh.
- [x] . Comment delete without refresh.
- [x] . Added confirm before delete comment.
- [x] . Comment edit without refresh.
- [x] . Added cancel button when editing.
- [x] . Tagging user in comments.
- [x] . Added toggle to issue status button.
- [x] . Updated total number of bugs.
- [ ] . Tagged user would be notified through email
- [ ] . Reply to a comment

**Comment by farziengineer** [comment]
**Until final evaluations:**
- [x] . Add chart in domain
- [ ] . Follow/Unfollow a user
- [ ] . Upvote  an issue
- [ ] . Add ajax to All issue page
- [ ] . Search users using "user:<username>" and same for issues.

More issues will be added

**Comment by seanauriti** [comment]
Thank you, can you please update, would like to have 10+ tasks per person for final evaluations they can be a mix of issues in Github and new features to make the website better.
