### ISSUE TITLE
Raghav Jajodia - Enter in all of your tasks from your proposal into Github - split them into the weekly milestones

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#332]
https://drive.google.com/file/d/0ByKbEg1O-ES4alQxanBFVmRBWDA/view?pli=1

**Comment by jajodiaraghav** [comment]
List of tasks before mid-tern:
- [x] Add a search feature for issues/bugs
- [x] Add a search feature for users and domains
- [x] Improve design for allauth pages
- [x] Add copy-to-clipboard feature
- [x] Improvements to avatar upload
- [ ] Monthly summary on stats
- [ ] popover for user in _activity
- [ ] popover for domain in _activity
- [ ] Pagination in required lists
- [ ] Design of header
- [ ] Styling the lightbox plugin
- [ ] Add "Team pages"
- [ ] popover for user and domain in _activity

**Comment by jajodiaraghav** [comment]
List of tasks after mid-term:

- [ ] Add "Team" pages
- [ ] Show issue type distribution in /domain
- [ ] Add Pie-chart for issue distribution in /stats
- [ ] Revamp comments
- [ ] Add CSS linter
- [ ] Add ability to switch domain to another domain
- [ ] Update the wiki with some internal code-style guidelines

Will add more along the way.

**Comment by seanauriti** [comment]
Thank you, can you please update, would like to have 10+ tasks per person for final evaluations they can be a mix of issues in Github and new features to make the website better.
