### ISSUE TITLE
Siddharth Goyal - Enter in all of your tasks from your proposal into Github - split them into the weekly milestones

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#333]
Proposal Title: Re-design of Bugheist front-end.

Proposal Description: The Bugheist website leaves a lot of scope to improve upon the user experience for everyone before further changes are to be made in the functioning of the tracker. 

For Desktop view:-
1. Creating a floating navigation bar in the website which has all the relevant links to different sections of the project.
2. Creating CSS cards for types of issues, for ex:, in number errors, on click/on hover a brief overlap which has description of the error and link(s) the examples to make it easy for anyone to understand and report bugs.
3. Redesign of latest activity section to create a grid of latest activities and change of the format of displaying latest activity.

Specifically for mobile view:-
1. Floating nav bar will have all the links compressed in a modern burger icon to ensure user sees more relevant content on mobile. 
2. Redesign of bug-reporting section for mobile view for easy input.
3. Redesign of latest activity section for scaling on mobile view.
4. Implementation of a proper footer optimized for scaling across multiple screen sizes.

Timeline:-
July 3 - July 31:- All Desktop view changes

August 7 - September 1 - All mobile view changes.

**Comment by seanauriti** [comment]
@goyal-sidd can you please add these to github under separate issues or at least make this a task list and show what you have done so far?  Because this will help track progress for the evaluations.

**Comment by goyal-sidd** [comment]
**Until mid-term evaluations**

- [ ] Responsive cards for errors 
- [ ] Added onto search functionality for labels
- [ ] Examples for all types of errors using added label search
- [ ] Implementation of Footer (Desktop)
- [ ] Implementation of Footer (Mobile)
- [ ] Functionality to check for bug domain in report
- [ ] Added graph for stats on number of bugs reported
- [ ] Button to report bugs on mobile 

General:
Streamlined front end code, by removing all inline CSS [#348],
Other: [#373]

**Comment by goyal-sidd** [comment]
**Until final evaluations**

- [ ] Pagination for company scoreboard
- [ ] Pagination of domain specific issues.
- [ ] List bugs by type for user profiles
- [ ] Allow reporting of hardware issues

will add more issues with time.

**Comment by seanauriti** [comment]
Thank you.  Please focus on remaining issues in Github issues.
