### ISSUE TITLE
Sourav Badami - Enter in all of your tasks from your proposal into Github - split them into the weekly milestones

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#334]
https://docs.google.com/document/d/1sh2bdhTHzKnLJpSpAGZpUipMYRNZSCg-p3HBBDA9NZ8/edit?usp=sharing

**Comment by souravbadami** [comment]
**Until Mid Term Evaluation:** 

_Backend Workflow:_

- [ ] Travis CI integration.
- [ ] Vagrant development server implementation.
- [ ] Integrating code compression on production site.
- [ ] Python linter.
- [ ] JavaScript linter.
- [ ] Refactoring code base to by pass new linter definition.
- [ ] Adding the new linter tests to Travis CI.

_General ( Updating along the way ):_

- [ ] New issues page for adding issues and corresponding test.

**Comment by seanauriti** [comment]
Thanks for adding these.  I would prefer if we don't add code compression for now until we get more traffic because it's easier to debug the issues.   It would be good to add rollbar to the front-end to detect errors.  I would also like to discuss more tasks to build out the site for more functionality for companies and more ways to attract users to the website.

**Comment by seanauriti** [comment]
Thank you, can you please update, would like to have 10+ tasks per person for final evaluations they can be a mix of issues in Github and new features to make the website better.

**Comment by souravbadami** [comment]
Hi @seanauriti -- I've started updating them! Thanks!
