### ISSUE TITLE
Updates to bot

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#3353]
- [x] OWASP-BLT/BLT-Lettuce#85
- [x] OWASP-BLT/BLT-Lettuce#103
- [ ] OWASP-BLT/BLT#3635
- [ ] OWASP-BLT/BLT-Lettuce#84
- [x] OWASP-BLT/BLT-Lettuce#86
- [x] OWASP-BLT/BLT#3634
