### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#696]
This issue will be the main issue to keep track of all design changes for this next sprint.

- [ ] First we'd like to get all pages that are in the site into Figma
- [ ] Next, adapt the new design from figma to fit those pages that have not been designed yet - including these new screens - https://github.com/OWASP/BLT/issues/678
- [ ] Then convert the figma design into HTML and Flutter (using automated tools if possible - Check parabeac)

- [ ] #660 convert screenshots that are in figma to figma design elements
- [ ] #615 Integrate mobile design
- [ ] #586 Convert figma designs to HTML
- [ ] #589 Convert to HTML and integrate new newsletter template
- [ ] #588 Convert to HTML and integrate new start bughunt page
- [ ] #587 Convert to HTML and integrate new search page
- [ ] #585 Convert to HTML and integrate new dashboard
- [ ] #584 Convert to HTML and integrate new profile page
- [ ] #583 Convert to HTML and integrate new homepage

**Comment by ankit2001** [comment]
@fredfalcon , i am interested in doing this, looking forward to contribute.

**Comment by vibhuti019** [comment]
@fredfalcon I would like to contribute on this. Can you explain a bit more on what are the tasks which are completed and from where I will have to start.

**Comment by ankit2001** [comment]
Hi @vibhuti019, you are free to contribute to the project, join the slack group from 
here https://app.slack.com/client/T04T40NHX/C2FF0UVHU
The UI part is in Bugheist Org, you are free to contribute there in UI.
https://github.com/Bugheist/Flutter

**Comment by vibhuti019** [comment]
@ankit2001 it's not working asking for the slack worksace url😅

**Comment by fredfalcon** [comment]
@vibhuti019 feel free to take this issue you can type slash assign and it will assign to you.  All screens are open to new design.  Thank you!

**Comment by DonnieBLT** [comment]
This is a continual thing - let's make it easy for anyone to improve the design of any page by having a link to the figma document on each page as well as the source code and allow them to edit improve it at any time.
